import os
import time
import venv
from typing import Callable, List
from rich.console import Console
from rich.progress import Progress, SpinnerColumn, TextColumn

console = Console()

# Step functions
def create_project_dir(project_name: str):
    os.makedirs(project_name)
    time.sleep(0.3)
    console.log(f"[green]📁 Created folder: '{project_name}'[/green]")

def create_virtualenv(project_name: str):
    env_path = os.path.join(project_name, 'venv')
    venv.create(env_path, with_pip=True)
    console.log(f"[green]🐍 Virtual environment at: {env_path}[/green]")

def create_readme(project_name: str):
    readme_path = os.path.join(project_name, 'README.md')
    with open(readme_path, 'w') as f:
        f.write(f"# {project_name}\n\nGenerated by prefiq CLI.\n")
    time.sleep(0.3)
    console.log(f"[green]📝 README.md created in: {project_name}[/green]")

# Extensible step list
setup_steps: List[tuple[str, Callable[[str], None]]] = [
    ("Create project directory", create_project_dir),
    ("Create virtual environment", create_virtualenv),
    ("Create README", create_readme),
    # Add more steps as (label, function) tuples
]

def setup_folder(project_name: str):
    """Create a project folder with setup steps and rich progress."""

    if os.path.exists(project_name):
        console.print(f"[red]❌ Folder '{project_name}' already exists.[/red]")
        return

    console.print(f"\n[bold cyan]🚀 Starting setup for: '{project_name}'[/bold cyan]")

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        transient=True,
    ) as progress:
        for label, step_fn in setup_steps:
            task = progress.add_task(f"{label}...", start=True)
            try:
                step_fn(project_name)
            except Exception as e:
                console.print(f"[red]❌ Failed at '{label}': {e}[/red]")
                break
            progress.remove_task(task)

    console.print(f"\n[bold bright_green]✅ Setup complete for '{project_name}'![/bold bright_green]")
