import os
import time
import click
import venv
from rich.console import Console

console = Console()

@click.command()
@click.argument('project_name')
def install(project_name):
    """Create a project folder and set up environment."""

    if os.path.exists(project_name):
        console.print(f"[red]❌ Folder '{project_name}' already exists.[/red]")
        return

    console.print(f"[bold cyan]🚀 Setting up project: {project_name}[/bold cyan]")

    # Create directory
    os.makedirs(project_name)
    time.sleep(0.3)
    console.print(f"[green]📁 Folder created: {project_name}[/green]")

    # Virtualenv
    env_path = os.path.join(project_name, 'venv')
    with console.status("[yellow]Creating virtual environment...[/yellow]", spinner="dots"):
        time.sleep(1)
        venv.create(env_path, with_pip=True)
    console.print(f"[green]🐍 Virtual environment created at: {env_path}[/green]")

    # README
    readme_path = os.path.join(project_name, 'README.md')
    with open(readme_path, 'w') as f:
        f.write(f"# {project_name}\n\nGenerated by prefiq CLI.")
    time.sleep(0.3)
    console.print("[green]📝 README.md created[/green]")

    console.print("[bold bright_green]✅ Setup complete![/bold bright_green]")
